spring:
  application:
    name: serviceb
server:
  port: 8082

eureka:
  instance:
    # 心跳间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    hostname: 127.0.0.1
    appname: serviceb
  client:
    serviceUrl:
      defaultZone: http://alang:baihailangai001@euka1.com:8761/eureka/,http://alang:baihailangai001@euka2.com:8762/eureka/
