spring:
  application:
    name: servicea

server:
  port: 8084

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://alang:baihailangai001@euka1.com:8761/eureka/,http://alang:baihailangai001@euka2.com:8762/eureka/


management:
  endpoints:
    web:
      exposure:
        # 暴露所有 Web 指标
        include: "*"
      base-path: /actuator  # 默认就是 /actuator
  endpoint:
    info:
      enabled: true

