spring:
  application:
    name: servicea
server:
  port: 8081


eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://euka1.com:8761/eureka/,http://euka2.com:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics  # 确保包含 info
      base-path: /actuator  # 默认就是 /actuator
  endpoint:
    info:
      enabled: true