spring:
  security:
    user:
      name: alang
      password: baihailangai001
  application:
    name: eureka-server
server:
  port: 8762


eureka:
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
  client:
    serviceUrl:
      # eureka-server的地址
      defaultZone: http://alang:baihailangai001@euka1.com:8761/eureka/
    healthcheck:
      # 开启健康检查
      enabled: true
  instance:
    # 注册到eureka-server的实例名称
    hostname: euka2.com
    # metadata元数据
    metadata-map:
      dalao: baihailang2



management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics  # 确保包含 info
      base-path: /actuator  # 默认就是 /actuator
  endpoint:
    info:
      enabled: true