spring:
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      # eureka-server的地址
      defaultZone: http://euka1.com:8761/eureka/
  instance:
    # 注册到eureka-server的实例名称
    hostname: euka2.com
